### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'NBRMode')

### ISSUE THREAD

**Issue by 0xdhrv** [bloomreach/spa-sdk#16]
### Trace

```
TypeError: Cannot read properties of undefined (reading 'NBRMode')
    at BrPage.render (C:\dir\node_modules\@bloomreach\react-sdk\src\page\BrPage.tsx:129:36)
    at finishClassComponent (C:\dir\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5663:31)
    at renderClassComponent (C:\dir\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5696:3)
    at renderElement (C:\dir\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5943:7)
    at renderNodeDestructiveImpl (C:\dir\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\dir\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (C:\dir\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5920:3)
    at renderElement (C:\dir\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (C:\dir\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\dir\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
```

**Comment by joerideg** [comment]
Hi @0xdhrv i'm going to need a little more context than that :) 
Lets start with: 
- What Content version are you running, PaaS or SaaS?
-  What SDK versions are you running?
- Are you running CSR or SSR
- How does your config object look like that you pass into the BrPage component or initialize function

**Comment by beetlerom** [comment]
@0xdhrv Any updates on this?

**Comment by joerideg** [comment]
Closing this as inactive, @0xdhrv if you are still experiencing problems please leave a comment with more context and we will be happy to take a look.
